import cv2
import numpy as numpy
img1=cv2.imread('road.jpg')
#cv2.imshow('img1',img1)
img2=cv2.imread('car.jpg')
#cv2.imshow('img2',img2)

img2_gray=cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
weight=cv2.addWeighted(img1,1,img2,0.1,0)
ret,mask=cv2.threshold(img2_gray,210,255,cv2.THRESH_BINARY)
mask_inv=cv2.bitwise_not(mask)
#cv2.imshow('mask_inv',mask_inv)
road=cv2.bitwise_and(img1,img1,mask=mask)
#cv2.imshow('road',road)
car=cv2.bitwise_and(img2,img2,mask=mask_inv)
result=cv2.addWeighted(road,1,car,1.5,0)
cv2.imshow('reslut',result)
#cv2.imshow('ROAD',road)
#cv2.imshow('mask',mask)
#cv2.imshow('car',car)
sum=cv2.add(img2,img2,mask=mask)
#cv2.imshow("sum",sum)
cv2.waitKey(0)
cv2.destroyAllWindows()